backend:
  name: git-gateway
  branch: main

media_folder: 'static/images'
public_folder: '/images'
collections:
  - name: home_text
    label: home text
    folder: src/data/home_text
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text }
  - name: web_dev
    label: web dev
    folder: src/data/web_dev
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text }
      - { label: Featured Image, name: featured_image, widget: image }
